### ISSUE TITLE
Sort and filter packages by date, download count and stars

### ISSUE THREAD

**Issue by carlosalvidrez** [Meteor-Community-Packages/Packosphere#12]
It would be even more useful than atmosphere-js, if the tool allowed to sort packages by: 
release date
latest change date
number of downloads
number of stars

**Is your feature request related to a problem? Please describe.**
Yes, it is very hard to find trustworthy packages. 
The ability to sort by several criteria will help the community find the perhaps-not-yet popular packages that are modern, for example.

**Describe the solution you'd like**
Sorting criteria buttons on the search results screen, to sort and to filter by diverse criteria, as above.

**Describe alternatives you've considered**
I scroll, paginate, and then get frustrated and abandon the site.

**Comment by copleykj** [comment]
I am actually actively working on this for Packosphere. I'm not sure exactly how long it will take as I don't have a whole lot of time outside of paid projects and family life right now. Hopefully soon though.

**Comment by copleykj** [comment]
Just a minor update. I've got the UI for this just about done.. Once finished I'll start on the back end work. If I can pull together another couple working hours, I should be able to finish it up this week.

![image](https://user-images.githubusercontent.com/1511556/127720367-911b7352-c0a5-453a-8831-92ea5c13b466.png)

**Comment by copleykj** [comment]
I've just deployed the search filters functionality. There's definitely room for adding some filters, which I will do in the future. Some of them like sorting by most downloaded are going to require DB migrations and so I've left them out for the moment. For now I think even this limited set makes the search infinitely more useful.

**Comment by carlosalvidrez** [comment]
The date filter works great, thanks! If you’d like a hand with the app, let me know. I don’t have a lot of time available but could help out. I’d just need a 15 min setup tour so I can figure out how to install, test locally and push.

**Comment by copleykj** [comment]
Sure. 

I think all necessary setup info is included in the README. 

Feel free to ask any questions about the codebase in the #packosphere channel on the Meteor Community Slack workspace.
